### ISSUE TITLE
interchangeable use of "the organization that has published the Item” and ""the organization that has made the Item available”

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/rightsstatements.github.io#107]
the short description text of the NKC, CNE, NOC-NC and NOC-CR contain the phrase "the organization that has published the Item”, while we use "the organization that has made the Item available” elsewhere (consitently in the body of the statements). This should probably be harmonised (since the short description is not part of the statements proper, this should be considered a minor issue at this point. We should move on this quickly since this is something that will propagate through all translations)

**Comment by paul2keller** [comment]
by "short description" I am referring to the text that is called "One sentence description of the Rights Statement" in the white paper (the first text box in the tables)

**Comment by anarchivist** [comment]
Propose closing as `wontfix`; we can undertake this harmonization in a future version
