### ISSUE TITLE
Document editorial workflow for site content

### ISSUE THREAD

**Issue by literarymachine** [rightsstatements/rightsstatements.github.io#11]
From the minutes: "Allowing to edit the master branch, which automatically updates rightsstatements.github.io. Consequently we use rightsstatements.github.io as our staging environment."

**Comment by literarymachine** [comment]
Accidentally closed without review because of committing straight to `master`.

**Comment by literarymachine** [comment]
See https://github.com/rightsstatements/rightsstatements.github.io/blob/master/README.md

**Comment by anarchivist** [comment]
Minor change stemming from review - #13

**Comment by anarchivist** [comment]
Can we add a heading/paragraph to the top that describes how deployment works? (e.g. for someone like me, as opposed to content editors)
