### ISSUE TITLE
Add note when not viewing content on production site

### ISSUE THREAD

**Issue by literarymachine** [rightsstatements/rightsstatements.github.io#12]
From the minutes: "A short javascript message will be created to be displayed on the top of the page warning people that they are on a staging server when the domain is not rightsstatemens.org."

**Comment by literarymachine** [comment]
See http://rightsstatements.github.io/

**Comment by anarchivist** [comment]
:+1: Minor tweak - can we change the color of the links in the alert box to improve contrast?

**Comment by literarymachine** [comment]
> Minor tweak - can we change the color of the links in the alert box to improve contrast?

Definitely, I just did not touch any styles so far. This will be taken care of as part of #6.
