### ISSUE TITLE
implement minor changes as approved by Statements WG on 24-5-2018

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/rightsstatements.github.io#130]
Document containing the changes can be found here: https://github.com/rightsstatements/rightsstatements.github.io/blob/master/files/180524minor_changes_to_v1.0.pdf (or at https://docs.google.com/document/d/1UeoTOuUBLL7EsuJgLJdnayTmbucSPtRBJ6LQvDmy-A8/edit#heading=h.30j0zll). 

Update change-log once the statements are updated.

This is a precondition for deploying the DE translation

**Comment by paul2keller** [comment]
@aisaac it needs to be online together with the DE translation. preferably about 1/10000th of a nanosecond earlier. working on providing you with the DE translation files now

**Comment by anarchivist** [comment]
@paul2keller What is the expectation regarding the updates of the rights statements white paper for situations like this? The white paper includes the text of all the statements and I think we need to have some discussion about whether we should be rolling the updates in there as well.

**Comment by paul2keller** [comment]
see the last entry that we have at http://rightsstatements.org/en/documentation/changelog.html for how we have dealt with  this last time. i think we should follow this procedure, which requires the following actions: 

1) upload the document that approved the changes to rightsstatements.org/files/
2) upload an updated version of the white paper to rightsstatements.org/files/
3) add the change to the change log with links to both documents 

i can take care of creating the new version of the white paper and upload it to GitHub. i have already uploaded the approval document. and i can provide the text for the change log page, so that you can reply all of this together with the other changes

**Comment by anarchivist** [comment]
Thanks @paul2keller - sounds good.
