### ISSUE TITLE
Support for partial translations of site

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rightsstatements.github.io#133]
The [translation guidelines](http://rightsstatements.org/files/170612rs_translation_policy.pdf) encourage translation partners to translate the text of the home page and the about page. Now that the German translation is complete, we have a translation of the home page, the statements, and the page elements for the vocab page. 

How do we handle partial translations of the site? What impact does this have on navigation? If users are on a partially translated site, should they only see the pages that have translated into whatever the active locale is?

**Comment by paul2keller** [comment]
i think we should only show the translated pages. but we also need a way to switch to the more complete english version for users who come to the page via a translated locale. i guess that functionality does not exist yet, right?

**Comment by anarchivist** [comment]
This does not exist yet, correct.

**Comment by paul2keller** [comment]
is that something that we can easily fix? until we have a structural fix we should maybe add an info box on the home page in non english language versions. something like (in the translation language):

> You are viewing a limited version of the rightsstatements.org home page. The full website is available in english here.

**Comment by anarchivist** [comment]
I think this is probably doable if we have the text. We still need to make some determinations about how to exclude pages from the navigation as well.

**Comment by paul2keller** [comment]
if we offer a limited complexity / partial version to users who get to the site based on their browser language settings then we *must* alters them to the fact that there is more information available on the english language version.

if we send everyone to english as default and it they need to make a choice to see the translated version then i think this is not absolutely necessary.

i think this is something that we should add to our list of things to discuss in NYC on Thursday (that list is getting longish)

**Comment by puik** [comment]
I do not agree with @aisaac about not translating the page itself. I think having the site translated is very important for the outreach and awareness raising, for explaining the context etc.

I rather suggest *different translation policy/practice for the RS declarations and the rest of the site*. While the declarations' translations need to be very controlled, the rest of the site could be translated more freely – it needs to be on some i8n platform ([Crowdin](https://crowdin.com/) as @literarymachine suggested or [Transifex](https://www.transifex.com/) or [Translatewiki](https://translatewiki.net/)). I think having a situation where site is partially translated (as currently with German) is much messier and worse in the long run than having maybe not so strictly controlled translations.

Now that the declarations in German are online, will you proceed with Estonian?

**Comment by aisaac** [comment]
@puik I didn't say that translating the site is unimportant. I just said that we don't have the resources to do a full translation, and we are not in position to sort out a consistent policy for doing a partial translation. That is quite a difference.

About the idea of translating the rest of the site more freely, I think this can't fly. I've seen enough edition work on the rights statements to be sure that the people in charge of these won't like their strict editorial work to be undermined by some loose translation on pages next door. 
Even on "other" pages: I've been involved in changes for 'other parts' like http://rightsstatements.org/en/documentation/translations.html and the care that was given to every comma just doesn't fit the idea of a loose translation. One may say, 'yes it's a good idea let's make it happen' and then once it happens, as soon as there's a slight imprecision in translations, these will be re-edited, and re-edited, and re-edited...

**Comment by anarchivist** [comment]
From the 2018-06-07 WG chair meeting

* Show a limited version of the navigation, translated appropriately
* Link back to the English version of the website using a translated version of something like "More info (English)"

![screen shot 2018-06-07 at 11 29 48 am](https://user-images.githubusercontent.com/73732/41122726-76e8a92e-6a6a-11e8-8832-f6827eafc20c.png)
