### ISSUE TITLE
Do we need translations of error pages?

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rightsstatements.github.io#134]
Raised in discussion with @literarymachine in rightsstatements/rights-app#64: we don't currently have translations of the error pages for 406 or 404 errors, and these pages are not included in what we expect a translation partner to translate. Should we do this?

**Comment by paul2keller** [comment]
while it is probably relatively trivial to get these translated i would think that it is not really necessary, people will encounter 404 in english all the time and having to translated these only increases complexity

**Comment by aisaac** [comment]
As per co-chair meeting 6 June: we won't do it.
