### ISSUE TITLE
language selector

### ISSUE THREAD

**Issue by puik** [rightsstatements/rightsstatements.github.io#137]
Currently there is **no language selector** on the site to change the language of the site interface.

**Comment by paul2keller** [comment]
this is a known issue. we will discuss how we want to handle later this week and then come back here

**Comment by anarchivist** [comment]
@paul2keller Please provide the  resolution here from the Steering Committee meeting

**Comment by paul2keller** [comment]
@puik so we have discussed this at the SC meeting on friday and have come to the conclusion that for now we will maintain a minimalist approach here. This means that we are not offering an explicit language switcher on the site and continue to rely on content negotiation based on proffered browser language. (there is of course a navigation path from the english version of the homepage > translations overview page to the translated versions).

**Comment by puik** [comment]
I find it very strange and not at all user friendly decision.
I have written more under #138 and #139.

I believe none of these issues can be closed.
