### ISSUE TITLE
statements logotypes and titles clickable

### ISSUE THREAD

**Issue by puik** [rightsstatements/rightsstatements.github.io#145]
I suggest the logotypes and the titles (in red rectangles on the screenshot) of the individual declaration were also clickable (leading to the uri of the individual declaration).
![screen shot 2018-06-11 at 12 36 34 2 2](https://user-images.githubusercontent.com/2512379/41224189-838f8b4a-6d74-11e8-9238-fa3f72df8ff9.png)

**Comment by aisaac** [comment]
No objection from me at this stage.
