### ISSUE TITLE
Fix language-specific link to statement pages in header

### ISSUE THREAD

**Issue by aisaac** [rightsstatements/rightsstatements.github.io#146]
For all the discussion on #138 and my reluctance to have explicit links to language-specific versions of the statements, I believe that if we have a link to "Deklaratsioonid" at http://rightsstatements.org/page/1.0/?language=et, which has value http://rightsstatements.org/et/statements/, then that link should really direct to http://rightsstatements.org/page/1.0/?language=et

**Comment by puik** [comment]
Links like that sound a good solution.
(But I can't understand your reluctance to links to language-specific versions ;) @aisaac)
