### ISSUE TITLE
The "www" prefix sends you to a preview version (identical to github.io version)

### ISSUE THREAD

**Issue by patrickpeiffer** [rightsstatements/rightsstatements.github.io#150]
Example: [www.rightsstatements.org/en](http://www.rightsstatements.org/en) sends you to a version identical to [rightsstatements.github.io/en/](http://rightsstatements.github.io/en/).

This seems to apply to all pages, expect the statement detail pages such as [www.rightsstatements.org/page/NoC-CR/1.0/?language=en](http://www.rightsstatements.org/page/NoC-CR/1.0/?language=en)

Unsure if this is related to DNS or the server. Issue would ideally be resolved during the switch to https. Status: EV SSL certificate is currently in validation process.

**Comment by literarymachine** [comment]
> Example: www.rightsstatements.org/en sends you to a version identical to rightsstatements.github.io/en/.

The preview note simply checks if the URL is the canonical one, which is the one without the `www`. I think this should be solved by redirecting the `www` sub domain instead of delivering the content.

**Comment by literarymachine** [comment]
> Issue would ideally be resolved during the switch to https. 

Yes, we'll set up redirection of non-https to https then anyways!
