### ISSUE TITLE
Deploy via GitHub pages?

### ISSUE THREAD

**Issue by literarymachine** [rightsstatements/rightsstatements.github.io#3]
The easiest way to deploy the site accompanying rights-app is on GitHub pages. Ideally this would be the organizational account at rightsstatements.github.io because this plays well with the intended URL structure (i.e. exposing the static pages without a base path). Could you rename this repo to rightsstatements.github.io?

**Comment by literarymachine** [comment]
If deploying the site via GitHub pages is not an option, I would recommend an approach similar to rightsstatements/rights-app#40: let Travis build when a release is tagged, move the result to the server and expose it via Apache. Again, this heavily reduces the requirement on the target system (no Ruby/Gems/etc).

**Comment by anarchivist** [comment]
So, generally speaking, I'm in favor of deploying through GitHub pages, but I have two immediate concerns: 

* If possible, I'd like to discourage the use of <http://rightsstatements.github.io/> whenever possible, at the least for SEO reasons if nothing else. I think at a minimum we should address this by adding `<link/>` elements with `rel="canonical"` to the templates. If you have other suggestions here, they are welcome.
* The other concern is wanting potentially preview changes to the site in staging. Would this then require a different deployment process?

**Comment by literarymachine** [comment]
> The other concern is wanting potentially preview changes to the site in staging. Would this then require a different deployment process?

I have given this some thought and have come to the conclusion that no, this would not require a different deployment process. We can simply use the [gh-pages](https://github.com/rightsstatements/rightsstatements.github.io/tree/gh-pages) branch for staging as this also triggers a build but at a different URL. The staging server will then simply proxy there. I will reflect this in [rights-deploy](https://github.com/rightsstatements/rights-deploy).

**Comment by anarchivist** [comment]
Sounds good - thanks @literarymachine.

**Comment by literarymachine** [comment]
Unfortunately, what I recommended in https://github.com/rightsstatements/rightsstatements.github.io/issues/3#issuecomment-187324212 does not work. I see three options:

1. We could slightly modify https://github.com/rightsstatements/rightsstatements.github.io/issues/3#issuecomment-187324212 by using a fork of this repo and use the `gh-pages` branch there for staging. Unfortunately a fork cannot occur within the `rightsstatements` account, so one of the working group members would have to fork it and give the others access.
2. We could use an approach similar to the app deployment process, i.e. use release tagging to build the site and a playbook to deploy it.
3. We could go back to running jekyll on the servers.

I am strongly in favor of (1), because (2) and (3) make more steps - i.e. running a playbook - necessary  to add/update content. The least favorable to me is (3) because I have already spent a fair amount of time fighting with the whitelists of those servers and jekyll has quite a few dependencies.

**Comment by literarymachine** [comment]
Following up on our discussion during the development checkin, I'd like to get into the details of deploying the site a bit more. As mentioned, we can easily use Travis CI to build it for us but have to decide what actually triggers a build and where the resulting content is moved.

We could use a `master` and a `develop` branch. `master` is built and sent back to a `pages-production` branch, pull requests from `develop` to `master` trigger a build that is sent back to a `pages-staging`. `pages-production` and `pages-staging` are then exposed on the corresponding servers.

The question is if this is flexible enough because in this setup, always and only the latest pull request is available on staging.

**Comment by literarymachine** [comment]
See rightsstatements/rights-deploy@42c44a9a87b2e54771c94ee17bba1b216be0c5e8 and c29c8f7c42f8a197150660adc6027d1077c117ba.

**Comment by anarchivist** [comment]
I think I'm generally :+1: on this approach. (cc @no-reply @aisaac).

> The question is if this is flexible enough because in this setup, always and only the latest pull request is available on staging.

Perhaps we could look at adding the ability to [manually triggering builds](https://docs.travis-ci.com/user/triggering-builds/) for a given branch if need be?

**Comment by aisaac** [comment]
I can leave with the approach in general and don't mind if staging has the latest pull request. Actually in our context now, I think it might be counter-productive to introduce yet another level of flexibility. There won't be dozens of people willing to stage work on the same items at the same time!

**Comment by literarymachine** [comment]
#5 implements this.

**Comment by anarchivist** [comment]
Looks good. I'd like us to address #8 somewhat soon, which I just reported.

**Comment by anarchivist** [comment]
The one other issue is whether we want to capture errors upon push, which as we saw are not reported by Travis as a build failure. Thoughts?

**Comment by literarymachine** [comment]
I think we could `OR` the two `git push` commands to get a non-zero exit code when both fail:

    ([ "${TRAVIS_PULL_REQUEST}" = "false" ] && git push --force --quiet "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${PRODUCTION_TARGET_BRANCH} > /dev/null 2>&1) || ([ "${TRAVIS_PULL_REQUEST}" != "false" ] && git push --force --quiet "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${STAGING_TARGET_BRANCH} > /dev/null 2>&1)

**Comment by anarchivist** [comment]
That sounds good - thanks @literarymachine

**Comment by literarymachine** [comment]
FYI, returning a non-zero exit-code won't break a build in out current setup:

> The after_success, after_failure, after_script and subsequent stages do not affect the the build result.
https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build

Thus, I'll migrate to [script deployment](https://docs.travis-ci.com/user/deployment/script):

> If the script returns a nonzero status, deployment is considered a failure, and the build is marked “errored”.

**Comment by literarymachine** [comment]
> The one other issue is whether we want to capture errors upon push, which as we saw are not reported by Travis as a build failure. Thoughts?

I unfortunately think we are out of options here:

> Note that pull request builds skip deployment step altogether.
> https://docs.travis-ci.com/user/deployment/#Pull-Requests

Is reporting `git push` failures a serious issue? Any Jekyll build failures will trigger the actual build to fail.

**Comment by anarchivist** [comment]
> Is reporting `git push` failures a serious issue? Any Jekyll build failures will trigger the actual build to fail.

I think it's probably a nice to have feature, but for push failures, we could probably inspect the Travis logs. `git push --quiet` will only report errors. Do we need to redirect STDOUT and STDERR to null still in those cases even though we're still using `git push --quiet`?

**Comment by literarymachine** [comment]
> Do we need to redirect STDOUT and STDERR to null still in those cases even though we're still using git push --quiet?

I am afraid it will report

> Authentication failed for 'https://aabbccddPERSONALACCESSTOKENREDACTED@github.com/literarymachine/jekyll-bare.git/'

without that redirection. The best I can do is probably to output an error message in the log as in https://api.travis-ci.org/jobs/116483956/log.txt vs https://api.travis-ci.org/jobs/116488937/log.txt. If that does not suffice I must admit I'm a bit 404.

**Comment by literarymachine** [comment]
One more option I can see would be to trigger upon merges to `develop` and `master`, and not upon pull requests at all.

**Comment by anarchivist** [comment]
I'd be fine with the `WARNING` option. cc @no-reply @aisaac

**Comment by literarymachine** [comment]
> I'd be fine with the WARNING option. cc @no-reply @aisaac

Ok. Having spent quite some time with this issue now (sorry about this occupying so much space, the devil is in the details that I did not see it coming after switching from simply directly running Jekyll on the staging/production servers), I would probably favor the "build content upon merge" approach nevertheless. To summarize, this would imply the following:

- There are two branches, `develop` and `master`.
- Pull requests to those branches trigger a Travis test build.
- Only actual changes (i.e. merges or direct pushes) to those branches trigger a commit of the resulting site to `develop-pages` and `master-pages` respectively. If such a commit/push fails, this is directly visible here on GitHub.

This also circumvents the problem that "always and only the latest pull request is available on staging" (https://github.com/rightsstatements/rightsstatements.github.io/issues/3#issuecomment-190197479). Built site content always reflects the current state of `develop` and `master`.

See rightsstatements/rightsstatements.github.io#10.

**Comment by anarchivist** [comment]
OK, I think that's fine. To confirm:

* `develop => rights-stg.rightsstatements.org`
* `master => rights-prod.rightsstatements.org`

Is that correct?

**Comment by literarymachine** [comment]
Yes, but they move to the corresponding server via the intermediate page build branches `develop-pages` and `master-pages`. See rightsstatements/rights-deploy#3.

**Comment by anarchivist** [comment]
Got it - thanks. So in that case: 

* `develop => (build) => develop-pages => rights-stg.rightsstatements.org`
* `master => (build) => develop-master => rights-prod.rightsstatements.org`

**Comment by anarchivist** [comment]
I think the last thing we're missing is some documentation just to confirm the editing workflow.

**Comment by literarymachine** [comment]
> I think the last thing we're missing is some documentation just to confirm the editing workflow.

See #11.

> Got it - thanks. So in that case:
>
> - `develop => (build) => develop-pages => rights-stg.rightsstatements.org`
> - `master => (build) => master-pages => rights-prod.rightsstatements.org`

As discussed in the development check-in, we will slightly modify this again and use the `master` branch (and thus http://rightsstatements.github.io/) for staging as this enables quick iterations without the need to manually deploy:

- `master => (build by GitHub pages) => rightsstatements.github.io proxied to rights-stg.rightsstatements.org`
- `production => (build) => production-pages => rights-prod.rightsstatements.org`

The ansible playbook will be updated accordingly, see rightsstatements/rights-deploy#5. To avoid confusion, a note will be added on top of all Jekyll pages when the content is not viewed on the production server. See #12.

**Comment by anarchivist** [comment]
See rightsstatements/rights-app#51
