### ISSUE TITLE
Alignment of logos on partner page

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rightsstatements.github.io#37]
From Victor-Jan Vos:

> Alignment of the logos on the partner page is off http://rightsstatements.org/en/about.html

I'm wondering if it's because the logos have different aspect ratios, but I'm not certain.

**Comment by anarchivist** [comment]
@paul2keller adds: 

> agree, this should be fixed once all logos have been added. We currently have the following logos that need to be added: BnL, CC, NYPL and UM library. Mark should have svg files for all of them.
>
> the problem with the logos is that we currently have 7. so i guess that would be 2 rows of 3 and then a single one in the row below

These are in the `files` directory along with everything else.

**Comment by anarchivist** [comment]
I couldn't get 2 rows of 3 and one row of 1 to look right without guidance; keeping this open for future feedback, but I don't think it's ready yet without more feedback from the rest of the working group.

**Comment by anarchivist** [comment]
@literarymachine I don't think this is an urgent issue, but we should bring it back up if we have time or capacity later.

**Comment by aisaac** [comment]
This has not been raised as an issue by other consortium members.
