### ISSUE TITLE
Typography adjustments

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rightsstatements.github.io#41]
Reported by @paul2keller: 

> Overall the text sizes are too big (for my taste) and should be reduced. I would settle for something that is 85-90% of the current text sizes. (with the exception of the text size in the navigation bar which is fine as it is) 
>
> The font weight of H2 looks to heavy (if you compare it to the mockup done by Ryan (see below). I would suggest that we make it a little bit lighter.
>
> Reduce the overall width of all body text by 10-15% to make text easier to read.

This is the related issue previously mentioned to @literarymachine and @ryanjunell by email. As indicated, Felix had some questions about font sizes which were not necessarily clear in the Adobe Illustrator files sent by Ryan.

**Comment by anarchivist** [comment]
Comp in question:

![basictemplate v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111689/b54d9c44-f599-11e5-9a3f-4184a6ceddda.png)

**Comment by literarymachine** [comment]
@ryanjunell: Any chance you could provide us with font sizes for the above? Otherwise @j0hj0h will go with the approximations mentioned in https://github.com/rightsstatements/rightsstatements.github.io/issues/41#issue-150449774.

**Comment by anarchivist** [comment]
I think this is largely resolved, but I'm going to reassign this to @ryanjunell in case we get his feedback and there are operational changes we can make.
