### ISSUE TITLE
Implement page / layout for buttons and other assets

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rightsstatements.github.io#48]
I believe that this is the last critical thing we need done soon; see [#6 (comment)](https://github.com/rightsstatements/rightsstatements.github.io/issues/6#issuecomment-202924276). We still don't have FAQ content yet. Comp from  [#6 (comment)](https://github.com/rightsstatements/rightsstatements.github.io/issues/6#issuecomment-202924276).

![bdebd38e-f599-11e5-8224-c18de5499099](https://cloud.githubusercontent.com/assets/73732/14915541/ea07cb52-0de1-11e6-804e-6599276424cb.png)

This may be partially blocked by #47, but we could have a version of the page just linking to the SVG logo variations. Note that there are for versions of each logo.

**Comment by literarymachine** [comment]
On dev, see http://h2481931.stratoserver.net:4000/en/documentation/assets.html. Currently not accessible via the menu, should we add it back as a child of `Documentation`?

**Comment by anarchivist** [comment]
@literarymachine That sounds good - thanks!
