### ISSUE TITLE
Adjust layout of logos page

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rightsstatements.github.io#56]
@paul2keller proposes a streamlined version showing all the variants of a given logo grouped together by box, e.g., the variants of InC-OW-EU would all be grouped together.

Example:

![combined](https://cloud.githubusercontent.com/assets/73732/14990179/55713500-1129-11e6-8bc9-b0033ce00be7.png)

**Comment by anarchivist** [comment]
@literarymachine I think we're ready to start the work on this. We should only be displaying the blue and black versions as above; all other assets would be downloadable from a zip file.

**Comment by literarymachine** [comment]
On dev, see http://h2481931.stratoserver.net:4000/en/documentation/assets.html

**Comment by paul2keller** [comment]
looks good to me

**Comment by literarymachine** [comment]
> all other assets would be downloadable from a zip file

Is this ZIP file already available? And where would the link to the ZIP file go?

**Comment by paul2keller** [comment]
@literarymachine you can find the text for the page here: https://docs.google.com/document/d/1P8hvhbnhcjYqe7hHgkK9LAC_f2T-dpJPlWsPDxQc5fI/edit#heading=h.mjur7lnf76rv

**Comment by paul2keller** [comment]
i will am not quite sure where if we have he zip file yet. will look into that

**Comment by paul2keller** [comment]
here is the zip with all buttons: [rs_buttons_all.zip](https://github.com/rightsstatements/rightsstatements.github.io/files/486872/rs_buttons_all.zip)

i think it should go into: http://rightsstatements.org/files/buttons/rs_buttons_all.zip (and consequently the path to all the other buttons (the individual png and svg files) should be http://rightsstatements.org/files/buttons/

**Comment by paul2keller** [comment]
[rs_icons_all.zip](https://github.com/rightsstatements/rightsstatements.github.io/files/487056/rs_icons_all.zip) hi @literarymachine here is a zip file with all icons which contains the pdf versions as well.

i think it should go into: http://rightsstatements.org/files/icons/rs_icons_all.zip (and consequently the path to all the other icons (the individual png and svg files) should be http://rightsstatements.org/files/icons/

**Comment by literarymachine** [comment]
On beta: http://h2481931.stratoserver.net:4000/en/documentation/assets.html

IMHO the Icons-section would look better in a separate white box.

**Comment by paul2keller** [comment]
yes i agree that the icons section should go into its own box

**Comment by literarymachine** [comment]
> yes i agree that the icons section should go into its own box

On dev: http://h2481931.stratoserver.net:4000/en/documentation/assets.html
