### ISSUE TITLE
Implement templates

### ISSUE THREAD

**Issue by literarymachine** [rightsstatements/rightsstatements.github.io#6]

**Comment by ryanjunell** [comment]
![rs org v6_032116](https://cloud.githubusercontent.com/assets/5706103/13937072/964ddf2c-ef98-11e5-8e3c-defa4dcde914.png)

![rs org v6_032116 menu](https://cloud.githubusercontent.com/assets/5706103/13937073/965017ce-ef98-11e5-9675-0d1c1d0c92bc.png)

![rs org v6_032116 options](https://cloud.githubusercontent.com/assets/5706103/13937095/b0521bea-ef98-11e5-8cbc-4e723bfdc6e6.png)

**Comment by literarymachine** [comment]
Discussing these with @j0hj0h, we were wondering what these would look like on a wide screen? Are there any plans for responsiveness?

**Comment by ryanjunell** [comment]
these screenshots show the widescreen browser view... 

I can mockup the tablet and mobile views... they will be based on the responsiveness demonstrated here http://jekyll.blahlab.com

**Comment by ryanjunell** [comment]
![nav v2 1 settings_032816](https://cloud.githubusercontent.com/assets/5706103/14111664/998d16d8-f599-11e5-8587-e9a7d1cba9c5.png)

![nav v2 1 settings-expand_032816](https://cloud.githubusercontent.com/assets/5706103/14111665/998de8b0-f599-11e5-817f-96df6dcf1194.png)

**Comment by ryanjunell** [comment]
![footer v2 3 white_032816](https://cloud.githubusercontent.com/assets/5706103/14111673/a5ff7a96-f599-11e5-985e-c6d5e9c1c254.png)

**Comment by ryanjunell** [comment]
![basictemplate v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111689/b54d9c44-f599-11e5-9a3f-4184a6ceddda.png)

**Comment by ryanjunell** [comment]
![doc v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111700/bdec65a6-f599-11e5-9499-011747bbb3dc.png)

![doc faq v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111699/bdec1a1a-f599-11e5-8cd9-dde9ad36fbbb.png)

![doc buttons v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111698/bdebd38e-f599-11e5-8224-c18de5499099.png)

**Comment by ryanjunell** [comment]
![getinvolved v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111724/d1fbedd2-f599-11e5-9d73-5ab3710ed3d6.png)

**Comment by ryanjunell** [comment]
![statements top v2_032516](https://cloud.githubusercontent.com/assets/5706103/14111741/dfda2860-f599-11e5-8ba1-fe6aa39c352f.png)

![statements list v2 1_032816](https://cloud.githubusercontent.com/assets/5706103/14111740/dfd9d946-f599-11e5-9c54-6fb0dede4495.png)

**Comment by ryanjunell** [comment]
![mobile v1_032816](https://cloud.githubusercontent.com/assets/5706103/14111759/f27c412e-f599-11e5-833d-92f85fc45f27.png)

![mobile nav v1_032816](https://cloud.githubusercontent.com/assets/5706103/14111758/f27900fe-f599-11e5-93c8-50e73577b9e1.png)

**Comment by literarymachine** [comment]
Deployed an initial import of the theme (without any style adjustments) and the basic page structure to http://rightsstatements.github.io/

/cc @anarchivist @paul2keller @ryanjunell

**Comment by literarymachine** [comment]
ping @ebgore

**Comment by anarchivist** [comment]
Looking good initially. Thanks @literarymachine.

**Comment by ryanjunell** [comment]
![mtmitvhellstation rs](https://cloud.githubusercontent.com/assets/5706103/14251733/5a11552e-fa52-11e5-924c-1a65664137b7.png)

http://dp.la/item/c5b87d8f1cc44cc2765345ccafbb7a5b



![plate1 rs](https://cloud.githubusercontent.com/assets/5706103/14251734/5a1d4ab4-fa52-11e5-9545-0fd56d6b5d1b.png)

http://dp.la/item/fdeadf082a75adf79b5c1493c3f6e90a



![quilt rs](https://cloud.githubusercontent.com/assets/5706103/14251763/7970853e-fa52-11e5-99d8-9819b4656d48.png)

http://dp.la/item/e8c5dda3c8486f6d96f6223795cbb14b

**Comment by j0hj0h** [comment]
The letters r, s and u aren't displayed correctyl when using the Gotham font. See the following screenshot:

![bildschirmfoto 2016-04-04 um 19 19 55](https://cloud.githubusercontent.com/assets/3071485/14256640/4685c2e0-fa9a-11e5-8ffd-b1fcdb8cbf24.png)
