### ISSUE TITLE
http://rightsstatements.org/vocab/1.0/ gives 503

### ISSUE THREAD

**Issue by mzeinstra** [rightsstatements/rightsstatements.github.io#64]
![image](https://cloud.githubusercontent.com/assets/5627431/16189982/357cafe8-36dd-11e6-94d5-8134fd0aa271.png)

**Comment by literarymachine** [comment]
Back up and running: http://rightsstatements.org/page/1.0/?language=en

The last successfully handled request was `2016-06-19 19:08:47`, but the logs indicate no error after that. @anarchivist @no-reply @aisaac any chance you know / did something?

Leaving this open during further investigation.

**Comment by literarymachine** [comment]
BTW, http://rights-stg.rightsstatements.org/page/1.0/?language=en was also down. Did the hoster do anything I should be aware of?

**Comment by mzeinstra** [comment]
Given time differences with Mark, I forwarded the issue to Patrick Peiffer who is familiar with the hosters.

**Comment by literarymachine** [comment]
Apache log indicates an Apache restart at `Mon Jun 20 07:41:53.898780` which goes pretty much hand in hand with the first `503` of the rights-app at `[20/Jun/2016:07:42:47 +0200]`.

**Comment by anarchivist** [comment]
I contacted Conostix yesterday as I received an automated  message that the services were down. They contacted me about 6 hours ago and said that the hypervisor machine rebooted yesterday, and for some reason the VM didn't start automatically. They started the VM manually.

**Comment by literarymachine** [comment]
>  They contacted me about 6 hours ago and said that the hypervisor machine rebooted yesterday, and for some reason the VM didn't start automatically.

If I read this correctly, this is something out of scope of the rights-app.

> They started the VM manually.

The question would be if this startup process involved all usual init-scripts. The service did come back after previous restarts.
