### ISSUE TITLE
Add URIs to Human-Readable RightsStatements Pages

### ISSUE THREAD

**Issue by kestlund** [rightsstatements/rightsstatements.github.io#65]
URIs need to be added for reference to RightsStatements pages. E.g. http://rightsstatements.org/page/NoC-CR/1.0/

**Comment by aisaac** [comment]
Hi,

As promised, I've shown our page and issue (i.e. people using the wrong URI for the RS) to our UX specialist Panagiotis Kyrou.
I attach to this comment what he has designed. Two things to note:
- he thought that there's really a lot of empty space on the left of the page
- given our problem, he strongly suggests that there is a clear call to action next to the URI of the RS on the page.
Of course the suggestion should be refined, as Panos did this very quickly and we really didn't discuss tge wording, fontsize/color and shapes. But we have a good proposal to start working with!

Antoine

**Comment by aisaac** [comment]
@anarchivist how should we continue working on this?

**Comment by anarchivist** [comment]
Image for reference

![example](https://cloud.githubusercontent.com/assets/73732/17066308/75f984f6-5014-11e6-93f6-d825ce2b158e.jpg)

**Comment by anarchivist** [comment]
Following discussions with @paul2keller last week for the time being it was suggested that we just add the link to the bottom of the page:

![screen shot 2016-09-23 at 1 03 17 pm](https://cloud.githubusercontent.com/assets/73732/18795392/6d7b13d0-8192-11e6-85a8-06e194ea99c5.png)

Pull requests to implement this are #70 and rightsstatements/rights-app#57.

**Comment by anarchivist** [comment]
This was auto-closed. @aisaac, @kestlund: If this merits further discussion let me know on Basecamp.

**Comment by aisaac** [comment]
It's fine for me!

Antoine
