### ISSUE TITLE
change size of the icons displayed at the bottom of http://rightsstatements.org/en/documentation/assets.html

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/rightsstatements.github.io#74]
the three icons at the bottom are too big (there needs to be spacing between them). i would suggest to use the same size/layout as on http://rightsstatements.org/page/1.0/?language=en

**Comment by anarchivist** [comment]
fixed in http://rightsstatements.github.io/en/documentation/assets.html - deploying to prod.
