### ISSUE TITLE
add a bit of padding between the Qs and the As on http://rightsstatements.org/en/documentation/faq.html

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/rightsstatements.github.io#75]
when unfolded there needs to be more padding (whitespace) between the question and the answer text. I would suggest applying the same amount of padding as under the answer text (and above the next question)

**Comment by anarchivist** [comment]
Fix proposed in #79 looks like this:

![](http://g.recordit.co/Dl9dWwZItR.gif)
