### ISSUE TITLE
Bad link on FAQ page

### ISSUE THREAD

**Issue by drhansen1** [rightsstatements/rightsstatements.github.io#86]
On the [FAQ page ](http://rightsstatements.org/en/documentation/faq.html) under "For Cultural Heritage Institutions> How Can I Use These Statements," the "guidelines for applying the rights statements" link is broken 

Currently, the link points to http://rightsstatements.org/en/documentation/guidelines.html (page does not exist)
It should point to http://rightsstatements.org/en/documentation/usage_guidelines.html

**Comment by anarchivist** [comment]
Fixed in production: http://rightsstatements.org/en/documentation/faq.html
